# -*- coding: utf-8 -*-
"""analise_de_dados_bovespa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AklHOr5-wS3FID5NHgLhIXRKgqM6_KxW

Os dados usados no projeto se encontra nesse link:
https://drive.google.com/file/d/1MP3JfSvjZ8TcaVIRKmp3IVumJI-AW-0o/view?usp=share_link
"""

# importando as bibliotecas
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# importando o arquivo bovespa
from google.colab import files
arquivo = files.upload()

# data frame
df = pd.read_csv('all_bovespa.csv', delimiter=',')

df

# filtrar ações
df_itau = df[df['sigla_acao'] == 'ITUB4']
df_petro = df[df['sigla_acao'] == 'PETR4']
df_sinq = df[df['sigla_acao'] == 'SQIA3']

# filtrar as datas
# é possível escolher entre 2020-01-01 e 2022-12-31.

df_itau_2022=df_itau[df_itau['data_pregao']>='2022-11-01']
df_petro_2022=df_petro[df_petro['data_pregao']>='2022-11-01']
df_sinq_2022=df_sinq[df_sinq['data_pregao']>='2022-11-01']

# formatando as datas
df_itau['data_pregao']=pd.to_datetime(df_itau['data_pregao'],format='%Y-%m-%d')
df_itau = df_itau.set_index('data_pregao')

df_petro['data_pregao']=pd.to_datetime(df_petro['data_pregao'],format='%Y-%m-%d')
df_petro = df_petro.set_index('data_pregao')

df_sinq['data_pregao']=pd.to_datetime(df_sinq['data_pregao'],format='%Y-%m-%d')
df_sinq = df_sinq.set_index('data_pregao')

# grafico de tendencia
df_itau_2022['preco_fechamento'].plot(legend=True, label='Itau', figsize=(15,10))
df_petro_2022['preco_fechamento'].plot(legend=True, label='Petrobrás', figsize=(15,10))
df_sinq_2022['preco_fechamento'].plot(legend=True, label='Sinqia', figsize=(15,10))

# media móvel
df_itau_2022['mm7'] = df_itau_2022['preco_fechamento'].rolling(7).mean()
df_petro_2022['mm7'] = df_petro_2022['preco_fechamento'].rolling(7).mean()
df_sinq_2022['mm7'] = df_sinq_2022['preco_fechamento'].rolling(7).mean()

# médias móveis de 15 e 30 dias
dias = [15, 30]
for dia in dias:
  df_itau_2022['mm'+str(dia)] = df_itau_2022['preco_fechamento'].rolling(dia).mean()
  df_petro_2022['mm'+str(dia)] = df_petro_2022['preco_fechamento'].rolling(dia).mean()
  df_sinq_2022['mm'+str(dia)] = df_sinq_2022['preco_fechamento'].rolling(dia).mean()

# grafico  de tendencia e media movel
df_itau_2022[['preco_fechamento','mm7','mm15','mm30']].plot(legend= True, label = 'Itau', figsize=(15,10))

# grafico de tendencia e media movel
df_petro_2022[['preco_fechamento','mm7','mm15','mm30']].plot(legend= True, label = 'Petrobrás', figsize=(15,10))

# grafico  de tendencia e media movel
df_sinq_2022[['preco_fechamento','mm7','mm15','mm30']].plot(legend= True, label = 'Sinqia', figsize=(15,10))

# calculo de retorno diario
df_itau_2022['retorno_diario'] = df_itau_2022['preco_fechamento'].pct_change()
df_petro_2022['retorno_diario'] = df_petro_2022['preco_fechamento'].pct_change()
df_sinq_2022['retorno_diario'] = df_sinq_2022['preco_fechamento'].pct_change()

# grafico de retorno diario
df_itau_2022['retorno_diario'].plot(legend= True, label = 'Itau', figsize=(15,10))

# grafico de retorno diario
df_petro_2022['retorno_diario'].plot(legend= True, label = 'Patrobrás', figsize=(15,10))

# grafico de retorno diario
df_sinq_2022['retorno_diario'].plot(legend= True, label = 'Sinqia', figsize=(15,10))

# grafico da probabilidade de retorno diario 

fig , axes = plt.subplots(3, figsize= (18,10))

fig.suptitle('Probabilidade de Retorno diário')

sns.distplot(df_itau_2022['retorno_diario'], bins = 100, axlabel='Retorno diario - Itaú', ax=axes[0])
sns.distplot(df_petro_2022['retorno_diario'], bins = 100, axlabel='Retorno diario - Petrobrás', ax=axes[1])
sns.distplot(df_sinq_2022['retorno_diario'], bins = 100, axlabel='Retorno diario - Sinqia', ax=axes[2])

# analise de correlação 

df_all = pd.DataFrame({'Itau': df_itau_2022['preco_fechamento'],
                       'Petrobrás': df_petro_2022['preco_fechamento'],
                       'Sinqia': df_sinq_2022['preco_fechamento']})

corr = df_all.corr()

corr

# heatmap
sns.heatmap(corr, annot=True)

# risco x retorno
retorno_itau = df_itau_2022.retorno_diario.dropna().mean()
risco_itau = df_itau_2022.retorno_diario.dropna().std()

retorno_petro = df_petro_2022.retorno_diario.dropna().mean()
risco_petro = df_petro_2022.retorno_diario.dropna().std()

retorno_sinq = df_sinq_2022.retorno_diario.dropna().mean()
risco_sinq = df_sinq_2022.retorno_diario.dropna().std()

print('Retorno Itau: ', retorno_itau, 'Risco Itaú: ', risco_itau)
print('Retorno Petrobrás: ', retorno_petro, 'Risco Petrobrás: ', risco_petro)
print('Retorno Sinqia: ', retorno_sinq, 'Risco Sinqia: ', risco_sinq)

# gráfico risco x retorno

plt.grid()
plt.xlabel('Média esperada retorno diario')
plt.ylabel('Risco diario')
plt.scatter(retorno_itau, risco_itau, marker='*')
plt.scatter(retorno_petro, risco_petro, marker='^')
plt.scatter(retorno_sinq, risco_sinq, marker='+')